// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui_gas

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_uiLabelGasValue;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_uiArcGas;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_uiLabelState;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_uiBtnValve;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_uiBtnExtractor;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_uiLabelWifi;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_uiLabelIp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

