// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui_gas

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_uiLabelGasValue = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_uiArcGas = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_uiLabelState = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_uiBtnValve = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_uiBtnExtractor = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_uiLabelWifi = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_uiLabelIp = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_base_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 150);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -55);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xEA1818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelGasValue = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_uiLabelGasValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelGasValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelGasValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelGasValue, "0000");
    lv_obj_set_style_text_color(ui_uiLabelGasValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelGasValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelGasValue, &ui_font_normal26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -15);
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label2, "Gas level");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_normal10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiArcGas = lv_arc_create(ui_Panel1);
    lv_obj_set_width(ui_uiArcGas, 140);
    lv_obj_set_height(ui_uiArcGas, 140);
    lv_obj_set_align(ui_uiArcGas, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_uiArcGas, 38);
    lv_arc_set_bg_angles(ui_uiArcGas, 160, 20);
    lv_obj_set_style_arc_color(ui_uiArcGas, lv_color_hex(0x262525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_uiArcGas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_uiArcGas, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_uiArcGas, lv_color_hex(0x41A853), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_uiArcGas, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_uiArcGas, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_uiArcGas, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiArcGas, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 120);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_x(ui_Container1, lv_pct(0));
    lv_obj_set_y(ui_Container1, lv_pct(18));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "State");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_normal10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelState = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_uiLabelState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelState, 0);
    lv_obj_set_y(ui_uiLabelState, -36);
    lv_obj_set_align(ui_uiLabelState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelState, "NORMAL");
    lv_obj_set_style_text_color(ui_uiLabelState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelState, &ui_font_normal, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 70);
    lv_obj_set_height(ui_Container2, 70);
    lv_obj_set_y(ui_Container2, 15);
    lv_obj_set_x(ui_Container2, lv_pct(15));
    lv_obj_set_align(ui_Container2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiBtnValve = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_uiBtnValve, 70);
    lv_obj_set_height(ui_uiBtnValve, 70);
    lv_obj_set_align(ui_uiBtnValve, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBtnValve, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnValve, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnValve, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnValve, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnValve, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_uiBtnValve, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_uiBtnValve, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnValve, lv_color_hex(0x41AA52), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_uiBtnValve, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel2 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel2, 40);
    lv_obj_set_height(ui_Panel2, 40);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, lv_pct(-10));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, lv_pct(35));
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "VALVE");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_normal12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image3, &ui_img_1429767708);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -7);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 60);

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 70);
    lv_obj_set_height(ui_Container3, 70);
    lv_obj_set_y(ui_Container3, 15);
    lv_obj_set_x(ui_Container3, lv_pct(-15));
    lv_obj_set_align(ui_Container3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiBtnExtractor = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_uiBtnExtractor, 70);
    lv_obj_set_height(ui_uiBtnExtractor, 70);
    lv_obj_set_align(ui_uiBtnExtractor, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_uiBtnExtractor, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_uiBtnExtractor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnExtractor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnExtractor, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnExtractor, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnExtractor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_uiBtnExtractor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_uiBtnExtractor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnExtractor, lv_color_hex(0x41AA52), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_uiBtnExtractor, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel3 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel3, 40);
    lv_obj_set_height(ui_Panel3, 40);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, lv_pct(-10));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, lv_pct(35));
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "EXTRAC.");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_normal12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Image5, &ui_img_admirador_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image5, 0);
    lv_obj_set_y(ui_Image5, -7);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 70);

    ui_Container7 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 40);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, 140);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiLabelWifi = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_uiLabelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelWifi, "WIFI: WIFI_RED");
    lv_obj_set_style_text_color(ui_uiLabelWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelWifi, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_uiLabelWifi, lv_color_hex(0x8F2E2E), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_uiLabelWifi, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Container6 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_y(ui_Container6, 5);
    lv_obj_set_x(ui_Container6, lv_pct(0));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiLabelIp = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_uiLabelIp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelIp, "IP: 1.000.000.00.0");
    lv_obj_set_style_text_color(ui_uiLabelIp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelIp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelIp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_Panel1 = NULL;
    ui_uiLabelGasValue = NULL;
    ui_Label2 = NULL;
    ui_uiArcGas = NULL;
    ui_Container1 = NULL;
    ui_Label3 = NULL;
    ui_uiLabelState = NULL;
    ui_Container2 = NULL;
    ui_uiBtnValve = NULL;
    ui_Panel2 = NULL;
    ui_Label5 = NULL;
    ui_Image3 = NULL;
    ui_Container3 = NULL;
    ui_uiBtnExtractor = NULL;
    ui_Panel3 = NULL;
    ui_Label6 = NULL;
    ui_Image5 = NULL;
    ui_Container7 = NULL;
    ui_Container5 = NULL;
    ui_uiLabelWifi = NULL;
    ui_Container6 = NULL;
    ui_uiLabelIp = NULL;

}
