// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ui_gas

#ifndef _UI_GAS_UI_H
#define _UI_GAS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_base_png);    // assets/base.png
LV_IMG_DECLARE(ui_img_1429767708);    // assets/grifo (1).png
LV_IMG_DECLARE(ui_img_admirador_png);    // assets/admirador.png
LV_IMG_DECLARE(ui_img_basecarga_png);    // assets/baseCarga.png

// FONTS
LV_FONT_DECLARE(ui_font_light10);
LV_FONT_DECLARE(ui_font_normal);
LV_FONT_DECLARE(ui_font_normal10);
LV_FONT_DECLARE(ui_font_normal12);
LV_FONT_DECLARE(ui_font_normal26);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
